# Project: ch_ethz_csb_matlabscripting_util_LongFileNameToShort
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ch_ethz_csb_matlabscripting_util_LongFileNameToShort.o $(RES)
LINKOBJ  = ch_ethz_csb_matlabscripting_util_LongFileNameToShort.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" --no-export-all-symbols --add-stdcall-alias  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Program Files (x86)/Java/jdk1.6.0_23/include"  -I"C:/Program Files (x86)/Java/jdk1.6.0_23/include/win32" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Program Files (x86)/Java/jdk1.6.0_23/include"  -I"C:/Program Files (x86)/Java/jdk1.6.0_23/include/win32" 
BIN  = ch_ethz_csb_matlabscripting_util_LongFileNameToShort.dll
CXXFLAGS = $(CXXINCS) -DBUILDING_DLL=1   -ansi
CFLAGS = $(INCS) -DBUILDING_DLL=1   -ansi
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ch_ethz_csb_matlabscripting_util_LongFileNameToShort.dll all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

DLLWRAP=dllwrap.exe
DEFFILE=libch_ethz_csb_matlabscripting_util_LongFileNameToShort.def
STATICLIB=libch_ethz_csb_matlabscripting_util_LongFileNameToShort.a

$(BIN): $(LINKOBJ)
	$(DLLWRAP) --output-def $(DEFFILE) --driver-name c++ --implib $(STATICLIB) $(LINKOBJ) $(LIBS) -o $(BIN)

ch_ethz_csb_matlabscripting_util_LongFileNameToShort.o: ch_ethz_csb_matlabscripting_util_LongFileNameToShort.cpp
	$(CPP) -c ch_ethz_csb_matlabscripting_util_LongFileNameToShort.cpp -o ch_ethz_csb_matlabscripting_util_LongFileNameToShort.o $(CXXFLAGS)
