/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ethz_csb_matlabscripting_util_LongFileNameToShort */

#ifndef _Included_ch_ethz_csb_matlabscripting_util_LongFileNameToShort
#define _Included_ch_ethz_csb_matlabscripting_util_LongFileNameToShort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_ethz_csb_matlabscripting_util_LongFileNameToShort
 * Method:    toShortFileName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_ethz_csb_matlabscripting_util_LongFileNameToShort_toShortFileName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
