name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Upload artifact as .zip
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: youscope.zip
        # Directory containing files to upload
        path: build/distributions/youscope.zip
    - name: Upload artifact as .tar
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: youscope.tar
        # Directory containing files to upload
        path: build/distributions/youscope.tar
